"""版本号管理模块
- 读取 VERSION 文件获取当前版本
- 构建时自动递增补丁号
- 生成 PyInstaller Windows 版本信息文件
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from datetime import datetime

PROJECT = Path(__file__).resolve().parent.parent
VERSION_FILE = PROJECT / "VERSION"

# PyInstaller 版本文件模板
VERSION_FILE_TEMPLATE = """# UTF-8
#
# Auto-generated by tools/version.py — DO NOT EDIT
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({v[0]}, {v[1]}, {v[2]}, {v[3]}),
    prodvers=({v[0]}, {v[1]}, {v[2]}, {v[3]}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'080404b0',
        [StringStruct(u'CompanyName', u'WeChatWorkAgent'),
        StringStruct(u'FileDescription', u'微信工作日报助手'),
        StringStruct(u'FileVersion', u'{vs}'),
        StringStruct(u'InternalName', u'WeChatWorkAgent'),
        StringStruct(u'LegalCopyright', u'Copyright (C) 2026'),
        StringStruct(u'OriginalFilename', u'WeChatWorkAgent.exe'),
        StringStruct(u'ProductName', u'微信工作日报助手'),
        StringStruct(u'ProductVersion', u'{vs}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [0x0804, 0x04b0])])
  ]
)
"""


def read_version() -> str:
    """读取当前版本号，如 '1.2.1'"""
    if VERSION_FILE.exists():
        return VERSION_FILE.read_text(encoding="utf-8").strip()
    return "1.0.0"


def parse_version(ver: str) -> tuple[int, int, int, int]:
    """解析版本字符串为四元组 (major, minor, patch, build)"""
    parts = ver.strip().split(".")
    nums = []
    for p in parts:
        try:
            nums.append(int(p))
        except ValueError:
            nums.append(0)
    # 补齐到 4 位
    while len(nums) < 4:
        nums.append(0)
    return (nums[0], nums[1], nums[2], nums[3])


def bump_version(ver: str | None = None, level: str = "build") -> str:
    """递增版本号，返回新版本字符串
    level: "build"(补丁+1) / "patch"(功能+1, build重置) / "minor"(小版本+1, patch/build重置) / "major"(大版本+1, 全部重置)
    """
    if ver is None:
        ver = read_version()
    v = parse_version(ver)
    if level == "major":
        new_ver = f"{v[0]+1}.0.0.0"
    elif level == "minor":
        new_ver = f"{v[0]}.{v[1]+1}.0.0"
    elif level == "patch":
        new_ver = f"{v[0]}.{v[1]}.{v[2]+1}.0"
    else:  # build
        new_build = v[3] + 1
        new_patch = v[2]
        if new_build > 99:
            new_build = 0
            new_patch += 1
        new_ver = f"{v[0]}.{v[1]}.{new_patch}.{new_build}"
    return new_ver


def save_version(ver: str) -> None:
    """将版本号写入 VERSION 文件"""
    VERSION_FILE.write_text(ver.strip(), encoding="utf-8")


def auto_bump() -> str:
    """自动递增版本号 → 写回文件 → 返回新版本"""
    old = read_version()
    new = bump_version(old)
    save_version(new)
    print(f"  版本号: {old} → {new}")
    return new


def format_version(ver: str) -> str:
    """格式化版本为显示字符串，如 'v1.2.1'"""
    v = parse_version(ver)
    # 如果 build 为 0，显示三位；否则显示四位
    if v[3] == 0:
        return f"v{v[0]}.{v[1]}.{v[2]}"
    return f"v{v[0]}.{v[1]}.{v[2]}.{v[3]}"


def generate_version_file(ver: str, output_path: Path | None = None) -> Path:
    """生成 PyInstaller 可用的 Windows 版本信息文件"""
    v = parse_version(ver)
    vs = format_version(ver).lstrip("v")  # "1.2.1" or "1.2.1.5"
    
    content = VERSION_FILE_TEMPLATE.format(v=v, vs=vs)
    
    if output_path is None:
        output_path = PROJECT / "build" / "version_info.txt"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def get_version_for_display() -> str:
    """获取用于界面显示的版本字符串"""
    return format_version(read_version())


def update_installer_iss(ver: str) -> None:
    """更新 installer.iss 中的版本号（保留完整版本号）"""
    iss_path = PROJECT / "installer.iss"
    if not iss_path.exists():
        print("  [!] installer.iss 不存在，跳过")
        return

    content = iss_path.read_text(encoding="utf-8")
    # 匹配: #define MyAppVersion "1.2.1" 或 "1.2.1.5"
    ver_str = ver.strip()
    new_content = re.sub(
        r'#define MyAppVersion\s+"[^"]*"',
        f'#define MyAppVersion "{ver_str}"',
        content,
    )
    if new_content != content:
        iss_path.write_text(new_content, encoding="utf-8")
        print(f"  已更新 installer.iss 版本号 → {ver_str}")


def update_run_py_version(ver: str) -> None:
    """更新 run.py 中的 __version__ 变量"""
    run_py = PROJECT / "run.py"
    if not run_py.exists():
        print("  [!] run.py 不存在，跳过")
        return

    content = run_py.read_text(encoding="utf-8")
    ver_str = ver.strip()
    new_content = re.sub(
        r'__version__\s*=\s*"[^"]*"',
        f'__version__ = "{ver_str}"',
        content,
    )
    if new_content != content:
        run_py.write_text(new_content, encoding="utf-8")
        print(f"  已更新 run.py __version__ -> {ver_str}")


def update_changelog(ver: str, message: str | None = None) -> None:
    """在 CHANGELOG.md 顶部插入新版本条目（如果还不存在）

    使用完整版本号（如 v2.0.1.13）作为去重标识，避免被同主次版本号
    的其他 build 条目误判为已存在。

    Args:
        ver: 版本号字符串
        message: 变更说明（可选）。缺省时仅打印提示，不写入空条目。
    """
    changelog_path = PROJECT / "CHANGELOG.md"
    if not changelog_path.exists():
        print("  [!] CHANGELOG.md 不存在，跳过")
        return

    # 用完整版本号作为 header，与 format_version 显示规则保持一致
    version_header = f"## {format_version(ver)}"
    today = datetime.now().strftime("%Y-%m-%d")

    content = changelog_path.read_text(encoding="utf-8")

    # 如果该完整版本号已存在，跳过（精确匹配，不再用前三段模糊匹配）
    if version_header in content:
        print(f"  CHANGELOG.md 中 {version_header} 已存在，跳过")
        return

    # 如果没有提供变更说明，拒绝写入空条目
    if not message or not message.strip():
        print(f"  [!] CHANGELOG.md 未更新：{version_header} 缺少 --message 变更说明，已跳过")
        print(f"      请手动编辑 CHANGELOG.md 或使用 --message 参数指定变更内容")
        return

    # 在第一行标题后插入新版本条目
    lines = message.strip().splitlines()
    if len(lines) == 1 and not lines[0].startswith("- "):
        # 单行简写，自动包装
        changelog_entry = f"- {lines[0]}"
    else:
        changelog_entry = "\n".join(f"- {line.lstrip('- ')}" if not line.startswith("- ") else line for line in lines)
    new_entry = f"{version_header} ({today})\n\n### 变更\n{changelog_entry}\n\n"
    # 找到第一个 ## 开头的位置之前插入
    first_section = content.find("\n## ", 1)  # 跳过标题行
    if first_section == -1:
        # 没有现有版本条目，追加到末尾
        new_content = content.rstrip() + "\n\n" + new_entry
    else:
        new_content = content[:first_section + 1] + new_entry + content[first_section + 1:]

    changelog_path.write_text(new_content, encoding="utf-8")
    print(f"  已更新 CHANGELOG.md -> {version_header} ({today})")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="版本号管理工具")
    sub = parser.add_subparsers(dest="cmd")

    _ = sub.add_parser("show", help="显示当前版本")
    p_bump = sub.add_parser("bump", help="递增版本号（自动写回 VERSION 文件）")
    p_bump.add_argument("--level", default="build", choices=["build", "patch", "minor", "major"],
                        help="递增级别: build(补丁+1) / patch(功能+1) / minor(小版本+1) / major(大版本+1)")

    gen_parser = sub.add_parser("gen-file", help="生成 PyInstaller 版本信息文件")
    _ = gen_parser.add_argument("--output", "-o", default=None, help="输出路径")

    update_parser = sub.add_parser("update-iss", help="更新 installer.iss 的版本号")
    _ = update_parser.add_argument("--ver", default=None, help="版本号（默认从 VERSION 读取）")

    run_parser = sub.add_parser("update-run", help="更新 run.py 的 __version__")
    _ = run_parser.add_argument("--ver", default=None, help="版本号（默认从 VERSION 读取）")

    changelog_parser = sub.add_parser("update-changelog", help="在 CHANGELOG.md 中添加新版本条目")
    _ = changelog_parser.add_argument("--ver", default=None, help="版本号（默认从 VERSION 读取）")
    _ = changelog_parser.add_argument("--message", "-m", default=None, help="变更说明（必填，缺省拒绝写入空条目）")

    sync_parser = sub.add_parser("sync-all", help="同步版本到所有文件（iss, run.py, changelog）")
    _ = sync_parser.add_argument("--ver", default=None, help="版本号（默认从 VERSION 读取）")
    _ = sync_parser.add_argument("--message", "-m", default=None, help="CHANGELOG 变更说明（缺省跳过 changelog 写入）")

    args = parser.parse_args()

    if args.cmd == "show":
        ver = read_version()
        print(f"当前版本: {format_version(ver)}")
        print(f"原始值:   {ver}")

    elif args.cmd == "bump":
        new = bump_version(level=args.level)
        save_version(new)
        print(f"新版本:   {format_version(new)}")

    elif args.cmd == "gen-file":
        ver = read_version()
        out = Path(args.output) if args.output else None
        path = generate_version_file(ver, out)
        print(f"已生成: {path}")

    elif args.cmd == "update-iss":
        ver = args.ver or read_version()
        update_installer_iss(ver)
        print("已更新 installer.iss")

    elif args.cmd == "update-run":
        ver = args.ver or read_version()
        update_run_py_version(ver)
        print(f"  run.py __version__ -> {ver}")

    elif args.cmd == "update-changelog":
        ver = args.ver or read_version()
        update_changelog(ver, getattr(args, "message", None))
        # 只有实际写入时才打印完成
        if getattr(args, "message", None):
            print("已更新 CHANGELOG.md")

    elif args.cmd == "sync-all":
        ver = args.ver or read_version()
        update_installer_iss(ver)
        update_run_py_version(ver)
        generate_version_file(ver)
        update_changelog(ver, getattr(args, "message", None))
        print("已同步所有文件（version_info.txt + installer.iss + run.py）")
        if getattr(args, "message", None):
            print("  + CHANGELOG.md")

    else:
        parser.print_help()
